### ISSUE TITLE
Allow for filename shorthand name.type.js

### ISSUE THREAD

**Issue by majgis** [majgis/ngify#14]
Annotations will trump the filename, but it might be handy to completely omit the annotation and use the file name format of name.type.js.

For example:

    apple.controller.js

would be equivalent to writing this annotation:

    exports['@ng'] = {
        name: 'apple',
        type: 'controller'
    }

If an '@ng' annotation is present, even if it is missing either type or name, the filename will be completely ignored.

**Comment by baens** [comment]
:+1:

**Comment by majgis** [comment]
@baens  There is a release candidate.  Execute the following to try it:

    npm install ngify@1.3.0-rc.1

View the [readme on github](https://github.com/majgis/ngify#file-name-parsing), npm still has dist-tag for latest set to 1.2.3
