### ISSUE TITLE
require('./template.html') should return the path registered with $templateCache

### ISSUE THREAD

**Issue by majgis** [majgis/ngify#23]
The following should work:

```
app.directive('test1', function (){
    return {
        templateUrl: require('./test3.html') // this returns a string 'test3.html'
}});
```

**Comment by Madd0g** [comment]
I soooo want this.

**Comment by majgis** [comment]
I'm working on this now, I'll most likely have it ready this evening.

**Comment by majgis** [comment]
This enhancement is in v1.4.1.

**Comment by Madd0g** [comment]
I'm having the same problem I had in issue #24.

      .state('main', {
             .....
             templateUrl: require('./main-template.html')
      })

This doesn't work unless I call it from the top of the script. If it's called from the state, it doesn't work. Shouldn't this work?

**Comment by majgis** [comment]
When the require statement is called, the following angular code is
executed:

```
angular.module('{moduleName}').run(['$templateCache',
function($templateCache){$templateCache.put('{templateName}','{html}')}])",
```

Most likely, the code in the run block is executing after it is needed.
You could try to hack the htmlTemplate setting to get an instance of the
$templateCache to immediately load the template.  Something along these
lines:

```
   htmlTemplate:
';angular.element(document.body).injector().get('$templateCache').put('{templateName}','{html}')}])
```

This is assuming you are bootstrapping to document.body, if you are
bootstrapping to a different element, you'll have to provide that element.

I don't recommend going this route.  Again, I recommend using
require-globify to immediately get objects registered with the injector.
