### ISSUE TITLE
Should nested requires work with the file-naming syntax?

### ISSUE THREAD

**Issue by Madd0g** [majgis/ngify#24]
I haven't changed anything besides using the filenaming syntax, but the inner requires stopped working, as soon as I moved them to index.js, everything started working. Have I done something wrong?

Index.js (has ui-router states)

      .state('main', {
             .....
             controller: require('./main.controller')
      })

and on top of `main.controller.js`:

       require('./common/thing1.directive');
       require('./common/thing2.directive');
       

      function mainCtrl()
      {
             
      }
      exports = module.exports = mainCtrl;

as soon as I move these directive requires to index.js, they work, but if they're in main.controller they don't work. Any idea why? I get no errors anywhere.

**Comment by majgis** [comment]
You might try the following:
```
var mainController = require('./main.controller')
.state('main', {
         .....
         controller: mainController
  })
```
Also, look in the bundled output to try and get an idea on what is happening, ie. is main.controller getting left out?

**Comment by Madd0g** [comment]
Main controller is the one that works. The directives it requires do not.

I peeked inside the generated bundle and both the directives and their inner templates are _there_, that's as useful as I can be (only started with browserify a couple of weeks ago).

Your suggestion works, but of course I would highly prefer not to separate it into a variable, because the states are chained - so the actual require ends up being very far from where it's used.

Thanks for the quick response, loving this library so far!

**Comment by majgis** [comment]
Ok, I'll do my best to recreate this issue, but I'll focus on getting the
other two issues resolved first.

**Comment by Madd0g** [comment]
So today I tested minification with ngify injections, it seems the problem with injections also happens with these nested requires. It looks like it's decorated in the bundle, but for some reason doesn't work. I spent a while on this today :(

This is just an FYI, because I tried ng-annotate today and prefer that solution, which requires less typing and leaves less room for mistakes.

**Comment by majgis** [comment]
Well, I'm not trying to compete with anyone.  I created a solution that
worked for my problem and shared it.  You are using ngify differently than
I am so maybe a different solution will suit you better.

**Comment by Madd0g** [comment]
ngify works great for me and I'm using all features except the injections, it all works together.

**Comment by majgis** [comment]
So one issue I see, is that you are trying to use the output of the require statements directly in angular.  Realize that requiring a file returns a generic JS object that might be used in a different framework.  If you   use ngify it inserts the extra angular boilerplate to register that object with Angular's dependency injection.  My advice is to use Angular's DI and not try to use the objects directly.  At first I thought I could support this usage, but ultimately with Angular, I think trying to bypass DI is a bad idea and will create many more problems.

For example, with the help of [require-globify](https://github.com/capaj/require-globify) I use the following to bulk load all files in the project:

```
//Create the module
require('./app');

//Load all .js files in the modules folder
require('./modules/**/*.js', {mode: 'expand', options:{ignore:'./modules/**/*.spec.js'}});

//Load all .html files in the modules folder
require('./modules/**/*.html', {mode: 'expand'});
```

Inside of ./app, I create the module, load submodules and immediate add odds and ends to the Angular's DI:

```
require('angular-route');
require('../../node_modules/angular-modal/modal.min');//Unminified version requires ng-annotate
require('angular-bootstrap-npm');
require('angular-animate');
require('rx-angular');

exports = module.exports = angular.module('mactApp', [
	'ngRoute',
	'btford.modal',
	'ui.bootstrap',
	'ngAnimate',
	'rx'
])
		.value('uriTemplates', require('uri-templates'))
		.value('moment', require('moment'))
		.value('underscore', _)
		.value('jQuery', jQuery)
		.value('Sly', Sly)
		.value('api_url', os.Otags.api_url)
		.value('angular', angular)
		.value('URIS', {
			RECS: '//www.overstock.com/api/recs'
		});
```

Now the rest of the application is declarative with zero angular boilerplate.  In very rare cases I'll use a require statement to inherit a subclass, but in all other cases I'm getting what I need from Angular's DI (Ask for what you want in the function signature).

If you try this paradigm shift, I think your experience with Angular will be even better.

**Comment by Madd0g** [comment]
hmm... I've seen multiple angular UMD projects where the exported thing is actually the name of the module ([example](https://github.com/urish/angular-moment/blob/master/angular-moment.js#L663), [example2](https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L10)), to support this syntax:
    
     angular.module('myModule', [ require('angular-moment'), require('angular-ui-router') ])

Since you're going to support this with templates, shouldn't this work the same?

**Comment by majgis** [comment]
It makes sense for the module to be returned, for example in ./app.js above, since that lives outside the injector, but everything else makes sense to access from Angular's DI.  It was a interesting idea at first, to return the angular object, but I can see no advantage to short circuiting Angular's DI.

In regard to the templates, they are unique, since you are registering the file name in the templatecache and not with the injector.  I'll give that some more thought and comment on that soon.
