### ISSUE TITLE
Have you seen ng-annotate/webpack?

### ISSUE THREAD

**Issue by kentcdodds** [majgis/ngify#25]
Cool library! I noticed that there's a bit of boilerplate in your code to use this plugin. If you haven't heard of [ng-annotate](https://github.com/olov/ng-annotate)? This will automatically add the annotations for you so you don't have to maintain them yourself. There's also [a browserify plugin](https://github.com/omsmith/browserify-ngannotate) (though, personally I recommend Webpack).

Also, with webpack, there's a loader for loading files as strings ([raw-loader](https://github.com/webpack/raw-loader) or [html](https://github.com/webpack/html-loader)). I'm sure there's an equivalent for that in Browserify. This would make it so you don't need to load things in the `$templateCache` but instead you'd simply do:

```
template: require('./the-template')
```

I hope this is helpful to you. I'm not trying to be pretentious, only helpful :-)

**Comment by majgis** [comment]
Yes, I'm familiar with ng-annotate, webpack and your zealotry for webpack.

In regard to webpack, I recognize that webpack is the right choice in many
cases, but in the cases where you don't want to throw in the kitchen-sink,
the simplicity of browserify is still a viable option.

In regard to ng-annotate and your suggestion that it adds boilerplate, I
think you have missed the point of the library.  It completely eliminates
angular boilerplate in favor of either a file naming convention or
annotations (think Angular 2.0).  This change gives you the ability to run
lightning fast unit tests, without using karma or jsdom or the ability to
use classes across frameworks.

Think of it more as a thought experiment.  Imagine not baking in framework
specific references throughout your code.  Imagine using the same
JavaScript POJO across frameworks. A similar plugin could be created for
webpack, but it is currently just an experiment that turned useful for one
of our projects.

**Comment by kentcdodds** [comment]
Ah, I think I may have missed the point of the library :-) Cool stuff! :dancer:
