### ISSUE TITLE
htmlparser missing

### ISSUE THREAD

**Issue by TheWoollyBully** [majgis/ngify#26]
```console
 Error compiling scripts: Cannot find module './htmlparser' from 'project/node_modules/ngify/node_modules/html-minifier/dist'
```

**Comment by majgis** [comment]
Thank you for reporting this issue, I'll have a look at it soon.

**Comment by majgis** [comment]
This issue appears to be with the html-minifier dependency.   I installed ngify and saw that file in place and experienced no issues.  

I have experienced issues with npm in the past, where the install is interrupted and packages are in a partially installed state.  Try deleting the node_modules/ngify folder and executing `npm i ngify`.

If that doesn't solve the problem, please provide more information on which version of node and npm you are using.

**Comment by TheWoollyBully** [comment]
I tried to install this several times over a couple of days but I was unable to get it working because of this issue. I used another solution instead. Sorry I cannot provide more info on why it wasn't working for me.
