### ISSUE TITLE
Parse error in HTML causes ngify to exit

### ISSUE THREAD

**Issue by ctucker** [majgis/ngify#9]
If invalid (not-well-formed) HTML content is passed to ngify, it will throw an exception rather than emitting an error.  This causes e.g. watch processes to exit rather than handle the error gracefully.

For example, attempting to ngify something like:

```html
<div
```

will cause htmlminifier to throw, which will just bubble up and cause the process to exit.

**Comment by majgis** [comment]
Thank you for bringing this issue to my attention. I will work on resolving this issue as soon as time permits.

**Comment by ctucker** [comment]
I'll have a PR for you in about 5 minutes. :-)

**Comment by majgis** [comment]
@ctucker , thanks for your PR.  I just published v0.1.2 to npm with your changes.
